import math


print(3 + 4)
print(3 - 4)
print(3 * 4)
print(3 / 4)
print(3 % 4)
print(3 ** 4)
print(3 // 4)
print('----------------------------------')
print("Noona")
print("Noor")
print("Indonesia")
print("I am enjoying with Python")
print('----------------------------------')
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4 - 4j))
print(type(['Krugger', 'Friend', 'Python']))
print(type("Noona"))
print(type('Noor'))
print(type('Indonesia'))
print(type(('Krugger', 'Friend', 'Python')))
print(type({'Krugger', 'Friend', 'Python'}))
print(type({'Krugger': 'Friend', 'Python': 'Noor'}))
print('----------------------------------')
print(math.sqrt((3 - 2)**2 + (10 - 8)**2))
